=== anhth2808/Libs/BaiTapXML/chuong4-bai8/QLDia.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="SPECIALS">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="TITLE" type="xs:string"></xs:element>
                <xs:element name="MESSAGE" type="xs:string"></xs:element>
                <xs:element name="CD" maxOccurs="unbounded">
                    <xs:complexType mixed="true">
                        <!-- chua xong simpleContent -->
                        <xs:sequence>
                            <xs:element name="ARTIST" type="xs:string"></xs:element>
                            <xs:element name="PRICEUS" type="xs:integer"></xs:element>
                            <xs:element name="PRICEVN" type="xs:integer"></xs:element>
                            <xs:element name="TRACK" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="length" use="required">                    
                                        <xs:simpleType>
                                            <xs:restriction base="xs:integer">
                                                <xs:minExclusive value="0"></xs:minExclusive>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                            
                        </xs:sequence>
                        
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== anhth2808/Libs/BaiTapXML/chuong4-bai8/instance2.xml
<?xml version="1.0" encoding="UTF-8"?>
<SPECIALS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/D:/Projects/BaiTapXML/chuong4-bai8/QLDia.xsd">
    <TITLE>TITLE0</TITLE>
    <MESSAGE>MESSAGE0</MESSAGE>
    <CD>
        <ARTIST>ARTIST0</ARTIST>
        <PRICEUS>0</PRICEUS>
        <PRICEVN>0</PRICEVN>
        <TRACK length="50"/>
        <TRACK length="50"/>
    </CD>
    <CD>
        <ARTIST>ARTIST1</ARTIST>
        <PRICEUS>0</PRICEUS>
        <PRICEVN>0</PRICEVN>
        <TRACK length="50"/>
        <TRACK length="50"/>
    </CD>
</SPECIALS>

=== anhth2808/Libs/BaiTapXML/chuong4-bai8/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="QLDia.xsl"?>
<SPECIALS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/D:/Projects/BaiTapXML/chuong4-bai8/QLDia.xsd">
    <TITLE>TITLE0</TITLE>
    <MESSAGE>MESSAGE0</MESSAGE>
    <CD>A hihi
        <ARTIST>Ai đó</ARTIST>
        <PRICEUS>12</PRICEUS>
        <PRICEVN>1200</PRICEVN>
        <TRACK length="50"/>A 1
        <TRACK length="50"/>A 2
    </CD>
    <CD>Ước mơ
        <ARTIST>Nghệ sĩ giàu hihi</ARTIST>
        <PRICEUS>50</PRICEUS>
        <PRICEVN>5000</PRICEVN>
        <TRACK length="50"/>Bài 1
        <TRACK length="50"/>Bài 2
    </CD>
    <CD>
        <ARTIST>Nghệ sĩ nghèo</ARTIST>
        <PRICEUS>11</PRICEUS>
        <PRICEVN>1100</PRICEVN>
        <TRACK length="50"/>Đoán xem
        <TRACK length="50"/>Không biết
    </CD>
</SPECIALS>
