=== anhth2808/Libs/BaiTapXML/chuong4-bai1/QLSV.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="QuanLyNhanVien">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="sinhvien" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MSSV">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="\d{7}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="HoTen" type="xs:string"></xs:element>
                            <xs:element name="Lop">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="CTK28|CTK28CD|CTK29|CTK29CD|CTK30"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="MonHoc" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="MaMonHoc">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[A-z][A-z][0-9][0-9]"></xs:pattern>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="TenMonHoc" type="xs:string"></xs:element>
                                        <xs:element name="SoTinChi">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:decimal">
                                                    <xs:minInclusive value="1.5"></xs:minInclusive>
                                                    <xs:maxExclusive value="5"></xs:maxExclusive>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="DiemmThi">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:decimal">
                                                    <xs:minInclusive value="0"></xs:minInclusive>
                                                    <xs:maxExclusive value="10"></xs:maxExclusive>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== anhth2808/Libs/BaiTapXML/chuong4-bai1/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<QuanLyNhanVien xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/D:/Projects/BaiTapXML/chuong4-bai1/QLSV.xsd">
    <sinhvien>
        <MSSV>0000000</MSSV>
        <HoTen>HoTen0</HoTen>
        <Lop>CTK28</Lop>
        <MonHoc>
            <MaMonHoc>AA00</MaMonHoc>
            <TenMonHoc>TenMonHoc0</TenMonHoc>
            <SoTinChi>2.75</SoTinChi>
            <DiemmThi>4.5</DiemmThi>
        </MonHoc>
        <MonHoc>
            <MaMonHoc>AA00</MaMonHoc>
            <TenMonHoc>TenMonHoc1</TenMonHoc>
            <SoTinChi>2.75</SoTinChi>
            <DiemmThi>4.5</DiemmThi>
        </MonHoc>
    </sinhvien>
    <sinhvien>
        <MSSV>0000000</MSSV>
        <HoTen>HoTen1</HoTen>
        <Lop>CTK28</Lop>
        <MonHoc>
            <MaMonHoc>AA00</MaMonHoc>
            <TenMonHoc>TenMonHoc2</TenMonHoc>
            <SoTinChi>2.75</SoTinChi>
            <DiemmThi>4.5</DiemmThi>
        </MonHoc>
        <MonHoc>
            <MaMonHoc>AA00</MaMonHoc>
            <TenMonHoc>TenMonHoc3</TenMonHoc>
            <SoTinChi>2.75</SoTinChi>
            <DiemmThi>4.5</DiemmThi>
        </MonHoc>
    </sinhvien>
</QuanLyNhanVien>
