=== anhth2808/Libs/BaiTapXML/chuong4-bai6/BanHangOnline.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="Inventorys">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Inventory" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    
    <xs:element name="Inventory">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Name">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[A-Z][1-9]{5}"></xs:pattern>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="InventoryID">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[A-Z][1-9]{5}"></xs:pattern>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="UnitPrice">
                    <xs:simpleType>
                        <xs:restriction base="xs:decimal">
                            <xs:minInclusive value="1.00"></xs:minInclusive>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="StockBin">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="B\d{3}"></xs:pattern>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    
</xs:schema>

=== anhth2808/Libs/BaiTapXML/chuong4-bai6/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Inventorys xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/D:/Projects/BaiTapXML/chuong4-bai6/BanHangOnline.xsd">
    <Inventory>
        <Name>A11111</Name>
        <InventoryID>A11111</InventoryID>
        <UnitPrice>50.5</UnitPrice>
        <StockBin>B000</StockBin>
    </Inventory>
    <Inventory>
        <Name>A11111</Name>
        <InventoryID>A11111</InventoryID>
        <UnitPrice>50.5</UnitPrice>
        <StockBin>B000</StockBin>
    </Inventory>
</Inventorys>
