=== anhth2808/Libs/BaiTapXML/chuong4-bai2/QuanLiDonHang.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="QuanLiDonHang">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="DonHang">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaKh">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-z][A-z][0-9][0-9]"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="TenKh" type="xs:string"></xs:element>
                            <xs:element name="DiaChi">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="\d{3}\c{10}"></xs:pattern> <!--Chua lam duoc-->
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="MacHang">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="MaMh">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[A-z][A-z][0-9][0-9]"></xs:pattern>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="TenMh" type="xs:string"></xs:element>
                                        <xs:element name="SoLuong">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:minExclusive value="0"></xs:minExclusive>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="DonGia">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:minExclusive value="0"></xs:minExclusive>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== anhth2808/Libs/BaiTapXML/chuong4-bai2/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<QuanLiDonHang xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/D:/Projects/BaiTapXML/chuong4-bai2/QuanLiDonHang.xsd">
    <DonHang>
        <MaKh>AA00</MaKh>
        <TenKh>TenKh0</TenKh>
        <DiaChi>000----------</DiaChi>
        <MacHang>
            <MaMh>AA00</MaMh>
            <TenMh>TenMh0</TenMh>
            <SoLuong>50</SoLuong>
            <DonGia>50</DonGia>
        </MacHang>
    </DonHang>
</QuanLiDonHang>
