=== anhth2808/Libs/BaiTapXML/old/bai2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="QLDH">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="KhachHang">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaKH" minOccurs="1" maxOccurs="1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="\s{2}\d{2}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="TenKH" type="xs:string" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="DiaChiKH" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="DSMatHang" minOccurs="1" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="MatHang" >
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="MaMatHang"  minOccurs="1" maxOccurs="1">
                                                      <xs:simpleType>
                                                          <xs:restriction base="xs:string">
                                                              <xs:pattern value="\s{2}\d{2}"></xs:pattern>
                                                          </xs:restriction>
                                                      </xs:simpleType>
                                                  </xs:element>
                                                  <xs:element name="TenMatHang" type="xs:string"/>
                                                  <xs:element name="SoLuong">
                                                      <xs:simpleType>
                                                          <xs:restriction base="xs:integer">
                                                              <xs:minInclusive value="0"></xs:minInclusive>
                                                          </xs:restriction>
                                                      </xs:simpleType>
                                                  </xs:element>
                                                    <xs:element name="DonGia">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:integer">
                                                                <xs:minInclusive value="0"></xs:minInclusive>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="MaKH">
            <xs:selector xpath="KhachHang"/>
            <xs:field xpath="MaKH"/>
        </xs:key>
        <xs:key name="MaMatHang">
            <xs:selector xpath="MatHang"/>
            <xs:field xpath="MaMatHang"/>
        </xs:key>
    </xs:element>
   
</xs:schema>

=== anhth2808/Libs/BaiTapXML/old/bai21.xml
<?xml version="1.0" encoding="UTF-8"?>
<QLDH xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/D:/Projects/BaiTapXML/bai2.xsd">
    <KhachHang>
        <MaKH>  00</MaKH>
        <TenKH>TenKH0</TenKH>
        <DiaChiKH>
        </DiaChiKH>
        <DSMatHang>
            <MatHang>
                <MaMatHang>  00</MaMatHang>
                <TenMatHang>TenMatHang0</TenMatHang>
                <SoLuong>50</SoLuong>
                <DonGia>50</DonGia>
            </MatHang>
        </DSMatHang>
    </KhachHang>
</QLDH>

=== anhth2808/Libs/BaiTapXML/old/bai2-test1.xml
<?xml version="1.0" encoding="UTF-8"?>
<QLDH xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/D:/Projects/BaiTapXML/bai2.xsd">
    <KhachHang>
        <MaKH>
        </MaKH>
        <TenKH>
        </TenKH>
        <DiaChiKH>
        </DiaChiKH>
        <DSMatHang>
            <MatHang>
                <MaMatHang>
                </MaMatHang>
                <TenMatHang>
                </TenMatHang>
                <SoLuong>
                </SoLuong>
                <DonGia>
                </DonGia>
            </MatHang>
        </DSMatHang>
    </KhachHang>
</QLDH>
