=== anhth2808/Libs/BaiTapXML/old/SinhVien.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="QuanLySinhVien">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="SinhVien" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaSv" type="xs:string"/>
                            <xs:element name="TenSv" type="xs:string"/>
                            <xs:element name="GioiTinh">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Nam"/>
                                        <xs:enumeration value="Ná»¯"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="NgaySinh" type="xs:date"/>
                            <xs:element name="MaLop">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Z][A-Z][A-Z][A-Z][0-9][0-9]"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== anhth2808/Libs/BaiTapXML/old/SinhVien3.xml
<?xml version="1.0" encoding="UTF-8"?>
<QuanLySinhVien xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/D:/Projects/BaiTapXML/SinhVien.xsd">
    <SinhVien>
        <MaSv>MaSv0</MaSv>
        <TenSv>TenSv0</TenSv>
        <GioiTinh>Nam</GioiTinh>
        <NgaySinh>2006-05-04</NgaySinh>
        <MaLop>AAAA00</MaLop>
    </SinhVien>
    <SinhVien>
        <MaSv>MaSv1</MaSv>
        <TenSv>TenSv1</TenSv>
        <GioiTinh>Nam</GioiTinh>
        <NgaySinh>2006-05-04</NgaySinh>
        <MaLop>AAAA00</MaLop>
    </SinhVien>
</QuanLySinhVien>

=== anhth2808/Libs/BaiTapXML/old/SinhVien1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="SinhVien.xsl"?>
<QuanLySinhVien xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="SinhVien.xsd">
    <SinhVien>
        <MaSv>MaSv0</MaSv>
        <TenSv>TenSv0</TenSv>
        <GioiTinh>Nam</GioiTinh>
        <NgaySinh>2006-05-04</NgaySinh>
        <MaLop>AAAA00</MaLop>
    </SinhVien>
    <SinhVien>
        <MaSv>MaSv1</MaSv>
        <TenSv>TenSv1</TenSv>
        <GioiTinh>Ná»¯</GioiTinh>
        <NgaySinh>2006-05-04</NgaySinh>
        <MaLop>AAAA00</MaLop>
    </SinhVien>
</QuanLySinhVien>
